import os
import streamlit as st
from openai import OpenAI

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    st.error("⚠️ OPENAI_API_KEY is not set in Heroku Config Vars")
else:
    client = OpenAI(api_key=api_key)